# -*- coding: utf-8 -*-
"""Vaishnavi_2021MT10930.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TV2kKQl1WUAzRky_o-yq6LygvgyaZms9

Alice's team consist of warriors with strength 3,4,6,7. My Entry number is 2021MT10930, My team consists of two warriors of strength 9,3. Now, for the first part of the question, I am stimulating a fight, and then a match between me and Alice Then I am randomly generating about 5000 of such cases, and then calculating the probability of my winning by dividing the my win time divided by total number of cases that we took For the first part, I have taken the maximum strategy i.e choosing the maximum strength warior in each scinario.
"""

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

# Generate random data for the inventory sheet
def generate_material_inventory_data(num_records):
    materials = ["Concrete", "Wood", "Steel", "Glass", "Drywall", "Insulation", "Tiles"]
    task_types = [
        "House Remodel", "Planning", "Demo Prep", "Demolition", "Excavation", "Concrete",
        "Pre backfill", "Framing", "Roof", "Plumbing", "Windows", "HVAC", "Electrical",
        "A/V", "House wrap", "Insulation", "Drywall", "Exterior stone", "Exterior case work",
        "Laundry/furnace room flooring", "Hardwoods", "Tile", "Cabinets", "Plumbing -hang sinks",
        "Interior doors", "Millwork", "Interior painting", "Stone Counters", "Schedule Buffer",
        "Decks", "Interior doors- hang & hardware", "Appliances", "Plumbing", "Electrical",
        "Bathroom Glass", "Garage Door dress up", "FINAL Inspections", "Wrap up", "House Cleaning"
    ]

    data = {
        "Material Name": [np.random.choice(materials) for _ in range(num_records)],
        "Material Id": [fake.uuid4() for _ in range(num_records)],
        "Quantity Purchased": np.random.randint(1, 500, num_records),
        "Unit Cost": np.random.uniform(5, 500, num_records).round(2),
        "Total Cost": [],
        "Supplier name": [fake.company() for _ in range(num_records)],
        "Supplier Ph. No": [fake.phone_number() for _ in range(num_records)],
        "Supplier Emai. id": [fake.email() for _ in range(num_records)],
        "Supplier Adress": [fake.address() for _ in range(num_records)],
        "Purchase Date": [fake.date_this_year() for _ in range(num_records)],
        "Project ID": [fake.uuid4() for _ in range(num_records)],
        "Task type": [np.random.choice(task_types) for _ in range(num_records)]
    }

    # Calculate Total Cost
    data["Total Cost"] = (data["Quantity Purchased"] * data["Unit Cost"]).round(2)

    return pd.DataFrame(data)

# Generate the data
num_records = 1000
material_inventory_data = generate_material_inventory_data(num_records)

# Save to CSV
material_inventory_data.to_csv('material_inventory.csv', index=False)

print("Material inventory CSV file has been generated successfully.")

from google.colab import drive
drive.mount('/content/drive')

import random
import time
#parts 1 and 2
# Function to simulate a single fight between two warriors
def fight(your_strength, alice_strength):
    total_strength = your_strength + alice_strength
    your_win_probability = your_strength / total_strength
    return random.random() < your_win_probability


# A single match between Alice and me
def match_max():
    my_warriors = [9, 3]  # my warrrior's strengths
    alice_warriors = [3, 4, 6, 7]  # Alice's warriors' strengths

    while len(my_warriors) != 0 and len(alice_warriors) != 0:
        # Alice picks a warrior randomly
        alice_strength = random.choice(alice_warriors)

        # You pick the warrior with the highest strength among your remaining warriors
        my_strength = max(my_warriors)

        # Fight between the chosen warriors
        win= fight(my_strength ,alice_strength)
        if win:
           alice_warriors.remove(alice_strength)
           my_warriors.remove(my_strength)
           my_warriors.append(my_strength + alice_strength)
        else:
            my_warriors.remove(my_strength)
            alice_warriors.remove(alice_strength)
            alice_warriors.append(alice_strength+ my_strength)
    if len(my_warriors) == 0:
        return False  # You lose the match
    else:
        return True  # You win the match

# Function to estimate the probability of winning based on multiple simulations
def estimate_max_probability(num_simulations):
    wins = 0
    for _ in range(num_simulations):
        if match_max():
            wins += 1

    # Calculate the estimated probability of winning
    probability = wins / num_simulations
    return probability


your_warriors = [9,3]
alice_warriors = [3, 4, 6, 7]

# Number of simulations
num_simulations = 5000

# Estimate probability of winning
probability_of_winning = estimate_max_probability( num_simulations)
print("Estimated probability of winning in max strategy:", probability_of_winning)

def match_min():
    my_warriors = [9, 3]  # my warrrior's strengths
    alice_warriors = [3, 4, 6, 7]  # Alice's warriors' strengths

    while len(my_warriors) != 0 and len(alice_warriors) != 0:
        # Alice picks a warrior randomly
        alice_strength = random.choice(alice_warriors)

        # You pick the warrior with the highest strength among your remaining warriors
        my_strength = min(my_warriors)

        # Fight between the chosen warriors
        win= fight(my_strength ,alice_strength)
        if win:
           alice_warriors.remove(alice_strength)
           my_warriors.remove(my_strength)
           my_warriors.append(my_strength + alice_strength)
        else:
            my_warriors.remove(my_strength)
            alice_warriors.remove(alice_strength)
            alice_warriors.append(alice_strength+ my_strength)
    if len(my_warriors) == 0:
        return False  # You lose the match
    else:
        return True  # You win the match

def estimate_min_probability(num_simulations):
    wins = 0
    for _ in range(num_simulations):
        if match_min():
            wins += 1
    # Calculate the estimated probability of winning
    probability = wins / num_simulations
    return probability


your_warriors = [9,3]
alice_warriors = [3, 4, 6, 7]

# Number of simulations
num_simulations = 5000

# Estimate probability of winning
probability_of_winning = estimate_min_probability( num_simulations)
print("Estimated probability of winning in min strategy:", probability_of_winning)

"""Now we notice that both come out to be around the same value of ~0.375. This fact is more visible when we take more number of iterations of the simulation.

## Calculation of Expected Gain

If Alice picks a warrior of strength x, and I pick a warrior of strength y, then the expectation value of gain for me is equal to:

$$
\
\text{Expected Gain} = \text{Probability of winning} \times \text{Gain on winning} + \text{Probability of losing} \times \text{Gain on losing}
$$



$$\
= \frac{x \times y}{x + y} - \frac{y \times x}{x + y}$$

$$\ = \frac{xy-xy}{x+y}$$

$$\ = 0 $$
As represented in the code too.
Thus, we see that each of the individual expectations is fair, meaning the expected gain is zero and the expected loss is also zero for both players.
"""

# Function to calculate the expected gain of strength
def expected_gain(my_strength, alice_strength):
    total_strength = my_strength + alice_strength
    return (alice_strength * (my_strength / total_strength)) - (my_strength* (alice_strength / total_strength))

possible_combinations = [(my_strength, alice_strength) for my_strength in [9, 3] for alice_strength in [3, 4, 6, 7]]

for my_strength, alice_strength in possible_combinations:
    print(f"Warrior strengths: Me: {my_strength}, Alice: {alice_strength}")
    expected_gain_strength = expected_gain(my_strength, alice_strength)
    print("Expected gain of strength:", expected_gain_strength)
    if abs(expected_gain_strength ) < 0.0001:
      print("The match is fair.")
    else:
      print("The match is not fair.")

# Check if the match is fair

def match_random():
    my_warriors = [9, 3]  # my warrrior's strengths
    alice_warriors = [3, 4, 6, 7]  # Alice's warriors' strengths

    while len(my_warriors) != 0 and len(alice_warriors) != 0:
        # Alice picks a warrior randomly
        alice_strength = random.choice(alice_warriors)

        # You pick the warrior with the highest strength among your remaining warriors
        my_strength = random.choice(my_warriors)

        # Fight between the chosen warriors
        win= fight(my_strength ,alice_strength)
        if win:
           alice_warriors.remove(alice_strength)
           my_warriors.remove(my_strength)
           my_warriors.append(my_strength + alice_strength)
        else:
            my_warriors.remove(my_strength)
            alice_warriors.remove(alice_strength)
            alice_warriors.append(alice_strength+ my_strength)
    if len(my_warriors) == 0:
        return False  # You lose the match
    else:
        return True  # You win the match

def estimate_random_probability(num_simulations):
    wins = 0
    for _ in range(num_simulations):
        if match_random():
            wins += 1
    # Calculate the estimated probability of winning
    probability = wins / num_simulations
    return probability


your_warriors = [9,3]
alice_warriors = [3, 4, 6, 7]

# Number of simulations
num_simulations = 5000

# Estimate probability of winning
probability_of_winning = estimate_random_probability( num_simulations)
print("Estimated probability of winning in random selection strategy:", probability_of_winning)

"""## Proof of pn(a, b) = a / (a + b)

For any $\ a, b, n \in \mathbb{N} $, let $\ p_n(a, b) $ be the probability of Alice winning when her army total is $\ a $, My army total is $\ b $, and there are \( n\) soldiers left between Alice and Mine **combined**. We will prove that (probability of me winning), $\ p_n(a, b) = \frac{a}{a + b} $ by induction on \( n \).

### Base Case (n = 1):
When there is only one soldier left in both Alice and Bob combined, there are two possible scenarios:
1. Alice's soldier is hte last one left. She wins the battle by sending a soldier with strength \( x \) and I lose. The probability of me winning in this scenario is 0
 $$ \frac{0}{x + 0} $$

$$\ = \frac{a}{a + b} $$

2. Alice loses the battle, and Bob wins. The probability of this scenario is $$  \frac{y}{x + y} $$

$$\ = \frac{a}{a + b} $$


Thus, the base case holds true.


### Inductive Step:

**Inductive Step (Assuming $\ p_k(a,b) = \frac{a}{a+b} \$ holds true for some \( k \)):**

Assume that Alice chooses a warrior with strength $ x$ and I choose a warrior with strength $y$. Then using Induction Hypotheis and  
$\text{TotalStrength} = \text{IntialStrength}+ ∑_{i≥1}gain_i$

$p_{k+1}(a,b) =  p(\text{I win match} | \text{I win war})*\frac{y}{x+y} + p(\text{I lose match} | \text{I win war})*\frac{x}{x+y}$

$=  \frac{(a+x)}{(a+x)+(b-x)}*\frac{y}{x+y} + \frac{(a-y)}{(a-y)+(b+y)}*\frac{x}{x+y}$

$ = \frac{(a+x)y}{(a+b)(x+y)} + \frac{(a-y)x}{(a+b)(x+y)}$

$= \frac{ay + yx +ax -yx}{(a+b)(x+y)}$

$= \frac{a(y+x)}{(a+b)(x+y)}$

$ = \frac{a}{a+b}$

Hence we proved that $p_k(a,b) = \frac{a}{a+b}$, by induction.

Thus, the proof is complete by induction.

In my case, the probability of winning is comming out to be $\ 12/20+12 = 0.375 $
Thus the probability of winning does not depend on the strategy of sendinng the players but the initial total strengths of the players. We also see through the simulations that all the three strategies i.e max, min and random gives a value of winning probability around the same value.

"""